//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.05 at 12:04:17 PM ADT 
//


package ca.unb.lib.riverrun.app.xmlui.aspect.sherparomeo.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "funder",
    "publishercomplies",
    "compliancetype",
    "selectedtitles"
})
@XmlRootElement(name = "mandate")
public class Mandate {

    @XmlElement(required = true)
    protected Funder funder;
    @XmlElement(required = true)
    protected String publishercomplies;
    @XmlElement(required = true)
    protected String compliancetype;
    protected List<Selectedtitles> selectedtitles;

    /**
     * Gets the value of the funder property.
     * 
     * @return
     *     possible object is
     *     {@link Funder }
     *     
     */
    public Funder getFunder() {
        return funder;
    }

    /**
     * Sets the value of the funder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Funder }
     *     
     */
    public void setFunder(Funder value) {
        this.funder = value;
    }

    /**
     * Gets the value of the publishercomplies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishercomplies() {
        return publishercomplies;
    }

    /**
     * Sets the value of the publishercomplies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishercomplies(String value) {
        this.publishercomplies = value;
    }

    /**
     * Gets the value of the compliancetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompliancetype() {
        return compliancetype;
    }

    /**
     * Sets the value of the compliancetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompliancetype(String value) {
        this.compliancetype = value;
    }

    /**
     * Gets the value of the selectedtitles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedtitles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedtitles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Selectedtitles }
     * 
     * 
     */
    public List<Selectedtitles> getSelectedtitles() {
        if (selectedtitles == null) {
            selectedtitles = new ArrayList<Selectedtitles>();
        }
        return this.selectedtitles;
    }

}
