//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.05 at 12:04:17 PM ADT 
//


package ca.unb.lib.riverrun.app.xmlui.aspect.sherparomeo.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.unb.lib.riverrun.app.xmlui.aspect.sherparomeo.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.unb.lib.riverrun.app.xmlui.aspect.sherparomeo.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Publishers }
     * 
     */
    public Publishers createPublishers() {
        return new Publishers();
    }

    /**
     * Create an instance of {@link Paidaccess }
     * 
     */
    public Paidaccess createPaidaccess() {
        return new Paidaccess();
    }

    /**
     * Create an instance of {@link Funder }
     * 
     */
    public Funder createFunder() {
        return new Funder();
    }

    /**
     * Create an instance of {@link Mandate }
     * 
     */
    public Mandate createMandate() {
        return new Mandate();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Selectedtitles }
     * 
     */
    public Selectedtitles createSelectedtitles() {
        return new Selectedtitles();
    }

    /**
     * Create an instance of {@link Postrestriction }
     * 
     */
    public Postrestriction createPostrestriction() {
        return new Postrestriction();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link Preprints }
     * 
     */
    public Preprints createPreprints() {
        return new Preprints();
    }

    /**
     * Create an instance of {@link Copyrightlinks }
     * 
     */
    public Copyrightlinks createCopyrightlinks() {
        return new Copyrightlinks();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Postrestrictions }
     * 
     */
    public Postrestrictions createPostrestrictions() {
        return new Postrestrictions();
    }

    /**
     * Create an instance of {@link Prerestriction }
     * 
     */
    public Prerestriction createPrerestriction() {
        return new Prerestriction();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Prerestrictions }
     * 
     */
    public Prerestrictions createPrerestrictions() {
        return new Prerestrictions();
    }

    /**
     * Create an instance of {@link Postprints }
     * 
     */
    public Postprints createPostprints() {
        return new Postprints();
    }

    /**
     * Create an instance of {@link Romeoapi }
     * 
     */
    public Romeoapi createRomeoapi() {
        return new Romeoapi();
    }

    /**
     * Create an instance of {@link Mandates }
     * 
     */
    public Mandates createMandates() {
        return new Mandates();
    }

    /**
     * Create an instance of {@link Copyrightlink }
     * 
     */
    public Copyrightlink createCopyrightlink() {
        return new Copyrightlink();
    }

    /**
     * Create an instance of {@link Journals }
     * 
     */
    public Journals createJournals() {
        return new Journals();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

}
