//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.05 at 12:04:17 PM ADT 
//


package ca.unb.lib.riverrun.app.xmlui.aspect.sherparomeo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parametername",
    "parametervalue"
})
@XmlRootElement(name = "parameter")
public class Parameter {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String source;
    protected String parametername;
    protected String parametervalue;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the parametername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametername() {
        return parametername;
    }

    /**
     * Sets the value of the parametername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametername(String value) {
        this.parametername = value;
    }

    /**
     * Gets the value of the parametervalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParametervalue() {
        return parametervalue;
    }

    /**
     * Sets the value of the parametervalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParametervalue(String value) {
        this.parametervalue = value;
    }

}
